[[redirects]]
  from = "/en-us/csea-voice"
  to = "https://app.logatot.com/csea-voice"
  status = 301
  force = false

[[redirects]]
  from = "/en-us/nafcc"
  to = "https://app.logatot.com/nafcc"
  status = 301
  force = false

[[redirects]]
  from = "/en-us/users/sign_up"
  to = "https://app.logatot.com/users/sign_up"
  status = 301
  force = false

[[redirects]]
  from = "/en-us/users/sign_in"
  to = "https://app.logatot.com/users/sign_in"
  status = 301
  force = false

[[redirects]]
  from = "/en-us/logins"
  to = "https://app.logatot.com/logins"
  status = 301
  force = false

[[redirects]]
  from = "/es-es/csea-voice"
  to = "https://app.logatot.com/csea-voice"
  status = 301
  force = false

[[redirects]]
  from = "/es-es/nafcc"
  to = "https://app.logatot.com/nafcc"
  status = 301
  force = false

[[redirects]]
  from = "/es-es/users/sign_up"
  to = "https://app.logatot.com/users/sign_up"
  status = 301
  force = false

[[redirects]]
  from = "/es-es/users/sign_in"
  to = "https://app.logatot.com/users/sign_in"
  status = 301
  force = false

[[redirects]]
  from = "/es-es/logins"
  to = "https://app.logatot.com/logins"
  status = 301
  force = false
