// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type PageDocumentDataSlicesSlice =
  | PricingFeatureSlice
  | FeatureContentSlice
  | FeatureGridSlice
  | TeamMemberGridSlice
  | VideosSlice
  | IFrameSlice
  | HeroSlice
  | TestimonialSlice
  | RegistrationSlice
  | PageHeaderSlice
  | CallToActionSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Main Nav*
 */
export interface SettingsDocumentDataMainNavItem {
  /**
   * Link Text field in *Settings → Main Nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.main_nav[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link URL field in *Settings → Main Nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.main_nav[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Item in *Settings → Footer Nav Website*
 */
export interface SettingsDocumentDataFooterNavWebsiteItem {
  /**
   * Link Text field in *Settings → Footer Nav Website*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_nav_website[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link URL field in *Settings → Footer Nav Website*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_nav_website[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Item in *Settings → Footer Nav Web App*
 */
export interface SettingsDocumentDataFooterNavWebAppItem {
  /**
   * Link Text field in *Settings → Footer Nav Web App*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_nav_web_app[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link URL field in *Settings → Footer Nav Web App*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_nav_web_app[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * CompanyName field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.companyname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  companyname: prismic.KeyTextField;

  /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Main Nav field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.main_nav[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_nav: prismic.GroupField<Simplify<SettingsDocumentDataMainNavItem>>;

  /**
   * Footer Nav Website field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_nav_website[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_nav_website: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavWebsiteItem>
  >;

  /**
   * Footer Nav Web App field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_nav_web_app[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_nav_web_app: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavWebAppItem>
  >;

  /**
   * Facebook Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_link: prismic.LinkField;

  /**
   * Twitter Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.twitter_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter_link: prismic.LinkField;

  /**
   * Instagram Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_link: prismic.LinkField;

  /**
   * LinkedIn Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.linkedin_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField;

  /**
   * Youtube Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.youtube_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_link: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type VideoLibraryDocumentDataSlicesSlice = PageHeaderSlice | VideosSlice;

/**
 * Content for Video Library documents
 */
interface VideoLibraryDocumentData {
  /**
   * Title field in *Video Library*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_library.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Video Library*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: video_library.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoLibraryDocumentDataSlicesSlice> /**
   * Meta Title field in *Video Library*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: video_library.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Video Library*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: video_library.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Video Library*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_library.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Video Library document from Prismic
 *
 * - **API ID**: `video_library`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoLibraryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<VideoLibraryDocumentData>,
    "video_library",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | PageDocument
  | SettingsDocument
  | VideoLibraryDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Headline field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Content field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Call To Action Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.call_to_action_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.LinkField;

  /**
   * Call To Action Link Text field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.call_to_action_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_link_text: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Signup → Primary*
 */
export interface CallToActionSliceSignupPrimary {
  /**
   * Headline field in *CallToAction → Signup → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.signup.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Content field in *CallToAction → Signup → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.signup.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Call To Action Link field in *CallToAction → Signup → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.signup.primary.call_to_action_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.LinkField;

  /**
   * Call To Action Link Text field in *CallToAction → Signup → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.signup.primary.call_to_action_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_link_text: prismic.KeyTextField;

  /**
   * SIgnup Button Endpoint field in *CallToAction → Signup → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.signup.primary.signup_button_endpoint
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  signup_button_endpoint: prismic.KeyTextField;

  /**
   * Signup Button Text field in *CallToAction → Signup → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.signup.primary.signup_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  signup_button_text: prismic.KeyTextField;
}

/**
 * Signup variation for CallToAction Slice
 *
 * - **API ID**: `signup`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceSignup = prismic.SharedSliceVariation<
  "signup",
  Simplify<CallToActionSliceSignupPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceSignup;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Item in *FeatureWithImageGroup → Default → Primary → Feature Group*
 */
export interface FeatureContentSliceSideBySidePrimaryFeatureGroupItem {
  /**
   * Header field in *FeatureWithImageGroup → Default → Primary → Feature Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_content.sideBySide.primary.feature_group[].header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * Content field in *FeatureWithImageGroup → Default → Primary → Feature Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_content.sideBySide.primary.feature_group[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *FeatureWithImageGroup → Default → Primary → Feature Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_content.sideBySide.primary.feature_group[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *FeatureWithImageGroup → Default → Primary*
 */
export interface FeatureContentSliceSideBySidePrimary {
  /**
   * Headline field in *FeatureWithImageGroup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_content.sideBySide.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Feature Group field in *FeatureWithImageGroup → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_content.sideBySide.primary.feature_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feature_group: prismic.GroupField<
    Simplify<FeatureContentSliceSideBySidePrimaryFeatureGroupItem>
  >;
}

/**
 * Default variation for FeatureWithImageGroup Slice
 *
 * - **API ID**: `sideBySide`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureContentSliceSideBySide = prismic.SharedSliceVariation<
  "sideBySide",
  Simplify<FeatureContentSliceSideBySidePrimary>,
  never
>;

/**
 * Slice variation for *FeatureWithImageGroup*
 */
type FeatureContentSliceVariation = FeatureContentSliceSideBySide;

/**
 * FeatureWithImageGroup Shared Slice
 *
 * - **API ID**: `feature_content`
 * - **Description**: FeatureContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureContentSlice = prismic.SharedSlice<
  "feature_content",
  FeatureContentSliceVariation
>;

/**
 * Item in *FeatureGrid → Default → Primary → Feature Items*
 */
export interface FeatureGridSliceDefaultPrimaryFeatureItemsItem {
  /**
   * Icon field in *FeatureGrid → Default → Primary → Feature Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.feature_items[].icon_selection
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_selection: prismic.SelectField<
    "Clock" | "Communication" | "Data" | "Mic"
  >;

  /**
   * Title field in *FeatureGrid → Default → Primary → Feature Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.feature_items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeatureGrid → Default → Primary → Feature Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.feature_items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Highlight Color field in *FeatureGrid → Default → Primary → Feature Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Red
   * - **API ID Path**: feature_grid.default.primary.feature_items[].highlight_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  highlight_color: prismic.SelectField<
    "Red" | "Orange" | "Pink" | "Blue" | "Purple",
    "filled"
  >;
}

/**
 * Primary content in *FeatureGrid → Default → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
  /**
   * Heading field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Feature Items field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.feature_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feature_items: prismic.GroupField<
    Simplify<FeatureGridSliceDefaultPrimaryFeatureItemsItem>
  >;

  /**
   * Content field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureGrid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault;

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: FeatureGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSlice = prismic.SharedSlice<
  "feature_grid",
  FeatureGridSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Images*
 */
export interface HeroSliceDefaultPrimaryImagesItem {
  /**
   * Image 1 field in *Hero → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[].image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Hero → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[].image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Hero → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[].image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Hero → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[].image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *Hero → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[].image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;
}

/**
 * Item in *Hero → Single Image → Primary → Images*
 */
export interface HeroSliceSingleImagePrimaryImagesItem {
  /**
   * Image 1 field in *Hero → Single Image → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleImage.primary.images[].image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;
}

/**
 * Item in *Hero → Landing Page → Primary → Images*
 */
export interface HeroSliceLandingPagePrimaryImagesItem {
  /**
   * Image 1 field in *Hero → Landing Page → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.images[].image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Headline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Content field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Call To Action 1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.call_to_action_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_1: prismic.LinkField;

  /**
   * Call To Action 1 Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.call_to_action_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_1_text: prismic.KeyTextField;

  /**
   * Call To Action 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.call_to_action_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_2: prismic.LinkField;

  /**
   * Call To Action 2 Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.call_to_action_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_2_text: prismic.KeyTextField;

  /**
   * Images field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Single Image → Primary*
 */
export interface HeroSliceSingleImagePrimary {
  /**
   * Headline field in *Hero → Single Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleImage.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Content field in *Hero → Single Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleImage.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Call To Action 1 field in *Hero → Single Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleImage.primary.call_to_action_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_1: prismic.LinkField;

  /**
   * Call To Action 1 Text field in *Hero → Single Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleImage.primary.call_to_action_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_1_text: prismic.KeyTextField;

  /**
   * Images field in *Hero → Single Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleImage.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HeroSliceSingleImagePrimaryImagesItem>>;
}

/**
 * Single Image variation for Hero Slice
 *
 * - **API ID**: `singleImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSingleImage = prismic.SharedSliceVariation<
  "singleImage",
  Simplify<HeroSliceSingleImagePrimary>,
  never
>;

/**
 * Primary content in *Hero → Landing Page → Primary*
 */
export interface HeroSliceLandingPagePrimary {
  /**
   * Headline field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Content field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Call To Action 1 field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.call_to_action_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_1: prismic.LinkField;

  /**
   * Call To Action 1 Text field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.call_to_action_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_1_text: prismic.KeyTextField;

  /**
   * Call To Action 2 field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.call_to_action_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_2: prismic.LinkField;

  /**
   * Call To Action 2 Text field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.call_to_action_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_2_text: prismic.KeyTextField;

  /**
   * Images field in *Hero → Landing Page → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.landingPage.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HeroSliceLandingPagePrimaryImagesItem>>;
}

/**
 * Landing Page variation for Hero Slice
 *
 * - **API ID**: `landingPage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceLandingPage = prismic.SharedSliceVariation<
  "landingPage",
  Simplify<HeroSliceLandingPagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceSingleImage
  | HeroSliceLandingPage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IFrame → Default → Primary*
 */
export interface IFrameSliceDefaultPrimary {
  /**
   * Title field in *IFrame → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: i_frame.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *IFrame → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: i_frame.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Default variation for IFrame Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IFrameSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IFrameSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IFrame*
 */
type IFrameSliceVariation = IFrameSliceDefault;

/**
 * IFrame Shared Slice
 *
 * - **API ID**: `i_frame`
 * - **Description**: IFrame
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IFrameSlice = prismic.SharedSlice<"i_frame", IFrameSliceVariation>;

/**
 * Primary content in *PageHeader → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * Headline field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Content field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Highlight Color field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.highlight_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  highlight_color: prismic.SelectField<
    "Red" | "Orange" | "Pink" | "Blue" | "Purple"
  >;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Item in *PricingFeature → Default → Primary → Features*
 */
export interface PricingFeatureSliceDefaultPrimaryFeaturesItem {
  /**
   * Feature Item field in *PricingFeature → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.features[].feature_item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_item: prismic.RichTextField;
}

/**
 * Item in *PricingFeature → Default → Primary → CTA Bullet Items*
 */
export interface PricingFeatureSliceDefaultPrimaryCtaBulletItemsItem {
  /**
   * CTA Item field in *PricingFeature → Default → Primary → CTA Bullet Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.cta_bullet_items[].cta_item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_item: prismic.RichTextField;
}

/**
 * Primary content in *PricingFeature → Default → Primary*
 */
export interface PricingFeatureSliceDefaultPrimary {
  /**
   * Headline field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Content field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Features field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<PricingFeatureSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * CTA Header field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.cta_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_header: prismic.RichTextField;

  /**
   * CTA Content field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.cta_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_content: prismic.RichTextField;

  /**
   * CTA Bullet Items field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.cta_bullet_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta_bullet_items: prismic.GroupField<
    Simplify<PricingFeatureSliceDefaultPrimaryCtaBulletItemsItem>
  >;

  /**
   * CTA Link URL field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.cta_link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_url: prismic.LinkField;

  /**
   * CTA Link Text field in *PricingFeature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_feature.default.primary.cta_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_link_text: prismic.KeyTextField;
}

/**
 * Default variation for PricingFeature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PricingFeature*
 */
type PricingFeatureSliceVariation = PricingFeatureSliceDefault;

/**
 * PricingFeature Shared Slice
 *
 * - **API ID**: `pricing_feature`
 * - **Description**: PricingFeature
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingFeatureSlice = prismic.SharedSlice<
  "pricing_feature",
  PricingFeatureSliceVariation
>;

/**
 * Primary content in *Registration → Default → Primary*
 */
export interface RegistrationSliceDefaultPrimary {
  /**
   * Headline field in *Registration → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Content field in *Registration → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Monthly Pricing Headline field in *Registration → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.default.primary.monthly_pricing_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  monthly_pricing_headline: prismic.KeyTextField;

  /**
   * Monthly Pricing Content field in *Registration → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.default.primary.monthly_pricing_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  monthly_pricing_content: prismic.RichTextField;

  /**
   * Yearly Pricing Headline field in *Registration → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.default.primary.yearly_pricing_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearly_pricing_headline: prismic.KeyTextField;

  /**
   * Yearly Pricing Content field in *Registration → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.default.primary.yearly_pricing_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  yearly_pricing_content: prismic.RichTextField;
}

/**
 * Default variation for Registration Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RegistrationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RegistrationSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Registration → Partner → Primary*
 */
export interface RegistrationSlicePartnerPrimary {
  /**
   * Headline field in *Registration → Partner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.partner.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Content field in *Registration → Partner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.partner.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Monthly Pricing Headline field in *Registration → Partner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.partner.primary.monthly_pricing_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  monthly_pricing_headline: prismic.KeyTextField;

  /**
   * Monthly Pricing Content field in *Registration → Partner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.partner.primary.monthly_pricing_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  monthly_pricing_content: prismic.RichTextField;

  /**
   * Yearly Pricing Headline field in *Registration → Partner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.partner.primary.yearly_pricing_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearly_pricing_headline: prismic.KeyTextField;

  /**
   * Yearly Pricing Content field in *Registration → Partner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: registration.partner.primary.yearly_pricing_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  yearly_pricing_content: prismic.RichTextField;
}

/**
 * Partner variation for Registration Slice
 *
 * - **API ID**: `partner`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RegistrationSlicePartner = prismic.SharedSliceVariation<
  "partner",
  Simplify<RegistrationSlicePartnerPrimary>,
  never
>;

/**
 * Slice variation for *Registration*
 */
type RegistrationSliceVariation =
  | RegistrationSliceDefault
  | RegistrationSlicePartner;

/**
 * Registration Shared Slice
 *
 * - **API ID**: `registration`
 * - **Description**: Registration
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RegistrationSlice = prismic.SharedSlice<
  "registration",
  RegistrationSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *TeamMemberGrid → Default → Primary → Team Members*
 */
export interface TeamMemberGridSliceDefaultPrimaryTeamMembersItem {
  /**
   * Image field in *TeamMemberGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_grid.default.primary.team_members[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamMemberGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_grid.default.primary.team_members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *TeamMemberGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_grid.default.primary.team_members[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TeamMemberGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_grid.default.primary.team_members[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * LinkedIn URL field in *TeamMemberGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_grid.default.primary.team_members[].linkedin_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_url: prismic.LinkField;
}

/**
 * Primary content in *TeamMemberGrid → Default → Primary*
 */
export interface TeamMemberGridSliceDefaultPrimary {
  /**
   * Team Members field in *TeamMemberGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_grid.default.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_members: prismic.GroupField<
    Simplify<TeamMemberGridSliceDefaultPrimaryTeamMembersItem>
  >;
}

/**
 * Default variation for TeamMemberGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMemberGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamMemberGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamMemberGrid*
 */
type TeamMemberGridSliceVariation = TeamMemberGridSliceDefault;

/**
 * TeamMemberGrid Shared Slice
 *
 * - **API ID**: `team_member_grid`
 * - **Description**: TeamMemberGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMemberGridSlice = prismic.SharedSlice<
  "team_member_grid",
  TeamMemberGridSliceVariation
>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Image field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Heading field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Quote field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Job Title field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Business Name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.business_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  business_name: prismic.KeyTextField;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Item in *Videos → Default → Primary → Video*
 */
export interface VideosSliceDefaultPrimaryVideoItem {
  /**
   * Title field in *Videos → Default → Primary → Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.video[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Videos → Default → Primary → Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.video[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Video URL field in *Videos → Default → Primary → Video*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.video[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;
}

/**
 * Primary content in *Videos → Default → Primary*
 */
export interface VideosSliceDefaultPrimary {
  /**
   * Video field in *Videos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.video[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  video: prismic.GroupField<Simplify<VideosSliceDefaultPrimaryVideoItem>>;

  /**
   * Combined Duration field in *Videos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 30 Minutes
   * - **API ID Path**: videos.default.primary.duration
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  duration: prismic.KeyTextField;
}

/**
 * Default variation for Videos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Videos*
 */
type VideosSliceVariation = VideosSliceDefault;

/**
 * Videos Shared Slice
 *
 * - **API ID**: `videos`
 * - **Description**: Videos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSlice = prismic.SharedSlice<"videos", VideosSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataMainNavItem,
      SettingsDocumentDataFooterNavWebsiteItem,
      SettingsDocumentDataFooterNavWebAppItem,
      VideoLibraryDocument,
      VideoLibraryDocumentData,
      VideoLibraryDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceSignupPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceSignup,
      FeatureContentSlice,
      FeatureContentSliceSideBySidePrimaryFeatureGroupItem,
      FeatureContentSliceSideBySidePrimary,
      FeatureContentSliceVariation,
      FeatureContentSliceSideBySide,
      FeatureGridSlice,
      FeatureGridSliceDefaultPrimaryFeatureItemsItem,
      FeatureGridSliceDefaultPrimary,
      FeatureGridSliceVariation,
      FeatureGridSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryImagesItem,
      HeroSliceDefaultPrimary,
      HeroSliceSingleImagePrimaryImagesItem,
      HeroSliceSingleImagePrimary,
      HeroSliceLandingPagePrimaryImagesItem,
      HeroSliceLandingPagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSingleImage,
      HeroSliceLandingPage,
      IFrameSlice,
      IFrameSliceDefaultPrimary,
      IFrameSliceVariation,
      IFrameSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      PricingFeatureSlice,
      PricingFeatureSliceDefaultPrimaryFeaturesItem,
      PricingFeatureSliceDefaultPrimaryCtaBulletItemsItem,
      PricingFeatureSliceDefaultPrimary,
      PricingFeatureSliceVariation,
      PricingFeatureSliceDefault,
      RegistrationSlice,
      RegistrationSliceDefaultPrimary,
      RegistrationSlicePartnerPrimary,
      RegistrationSliceVariation,
      RegistrationSliceDefault,
      RegistrationSlicePartner,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TeamMemberGridSlice,
      TeamMemberGridSliceDefaultPrimaryTeamMembersItem,
      TeamMemberGridSliceDefaultPrimary,
      TeamMemberGridSliceVariation,
      TeamMemberGridSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      VideosSlice,
      VideosSliceDefaultPrimaryVideoItem,
      VideosSliceDefaultPrimary,
      VideosSliceVariation,
      VideosSliceDefault,
    };
  }
}
