// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  feature_content: defineAsyncComponent(
    () => import("./FeatureWithImageGroup/index.vue"),
  ),
  feature_grid: defineAsyncComponent(() => import("./FeatureGrid/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  i_frame: defineAsyncComponent(() => import("./IFrame/index.vue")),
  page_header: defineAsyncComponent(() => import("./PageHeader/index.vue")),
  pricing_feature: defineAsyncComponent(
    () => import("./PricingFeature/index.vue"),
  ),
  registration: defineAsyncComponent(() => import("./Registration/index.vue")),
  rich_text: defineAsyncComponent(() => import("./Text/index.vue")),
  team_member_grid: defineAsyncComponent(
    () => import("./TeamMemberGrid/index.vue"),
  ),
  testimonial: defineAsyncComponent(() => import("./Testimonial/index.vue")),
  videos: defineAsyncComponent(() => import("./Videos/index.vue")),
});
